name: Build And Push Docker Image
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
jobs:
  images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: thibaultmorin/homecx
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
            {{major}}
      - name: Build and push the branch image
        uses: docker/build-push-action@v2
        if: startsWith(github.ref, 'refs/heads/')
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
